### ISSUE TITLE
RequestError when updating device serial number

### ISSUE THREAD

**Issue by etiensilvio205** [digitalocean/pynetbox#105]
Hello,
I am actually using Pynetbox to interface with my local Netbox and i am having issues doing a ".save()" on a device. 

Python code: 
`
    device=nb.dcim.devices.get(id=841,device_type_id=138,name="mydevice")
    device.serial=1234
    try:
	device.save()
     except pynetbox.RequestError as e:
	 print(e.error)`

Error:
`{"custom_fields":["Required field PFS cannot be empty."]}`

Please note that i am not doing `nb.dcim.devices.get(id=841)` as i am getting errors saying that the requests are returning multiple results even though i only have 1 device having this id.
I tried changing part numbers for device types the way im doing right now for serial numbers and it works just fine. The serial number update is just returning me the error specified up. Please help.

**Comment by zachmoody** [comment]
The kwargs you pass to `.get()` and `.filter()` simply get converted into URL parameters when it makes the netbox query. When you lookup a device by `id` you don't request `/devices/?id=123` you request `/devices/123/`. So to lookup something by ID `.get()` takes an argument that gets inserted into the URL in the right place. So your specific request should look something like `.get(841)` and that should return just that device; instead of all device because you passed an invalid URL param.

For the issue you're having with .save(), can you add the output of:
```
from pprint import pprint
pprint(dict(nb.dcim.devices.get(841))
```
