### ISSUE TITLE
Salt Netbox module functionality in pynetbox?

### ISSUE THREAD

**Issue by ngrundler** [digitalocean/pynetbox#131]
Hello,

We're starting to write scripts to get/create/update models in Netbox, and have found that the Salt Netbox module provides much of the functionality we need.  Rather than simply copying/rewriting the salt functions into our own module that we then need to maintain locally, we're thinking this sort of thing might be generally useful to others who are looking for a simple way to expose common pynetbox functions.  Would you consider incorporating the salt execution functions into pynetbox in some way?

I threw something like this together that I've been playing around with:
```
class Netbox():
    """
    basically just copy the salt netbox execution module functions into
    instance methods...
    """

    def __init__(self, url=None, token=None):
        self.url = url
        self.token = token


    def _nb_obj(self):
        """
        Returns an instance of pynetbox.Api
        """
        return pynetbox.api(self.url, self.token)


    def _dict(self, iterable):
        if iterable:
            return dict(iterable)
        else:
            return {}
    
    
    def _strip_url_field(self, input_dict):
        if 'url' in input_dict.keys():
            del input_dict['url']
        for k, v in input_dict.items():
            if isinstance(v, dict):
                self._strip_url_field(v)
        return input_dict


    def _get(self, app, endpoint, id=None, **kwargs):
        nb = self._nb_obj()
        if id:
            item = getattr(getattr(nb, app), endpoint).get(id)
        else:
            item = getattr(getattr(nb, app), endpoint).get(**kwargs)
        return item

   etc...
```

Does this seem useful?  We'd be happy to help contribute to this effort if you agree that it's a reasonable thing to do.

**Comment by zachmoody** [comment]
> Would you consider incorporating the salt execution functions into pynetbox in some way?

They're already there :smiley:. The Salt module's purpose is to expose pynetbox's functionality to Salt. There's been some recent changes to the Salt module that add some features beyond what's provided by pynetbox (the OpenConfig stuff, iirc). Is that what you're looking for? If not, could you give me an example pattern you're using that would benefit from having these functions in pynetbox itself?

**Comment by ngrundler** [comment]
Sure, take the `create_device` function in the salt module as an example.  If I want to create a device in my code, I'm going need to more or less write the exact same thing you did -- e.g. I need to ensure that the device name, role, and site all exist in netbox first, and then fetch their IDs before I POST a payload.  It's definitely not much code to write, but if you've already written it doesn't it make sense to just use that?

**Comment by zachmoody** [comment]
I see, that's definitely a neat idea. I'm a little concerned it may be a bit too focused for pynetbox though. Just an example off the top of my head might be that my requirements for a new device could go beyond just the fields NetBox requires. So now you're making two calls to the API per device because you _have_ to populate something like rack, or a custom_field, etc. That's not to say there aren't ways around that, but they kinda feel like a clumsy fit compared to what's already there.

I'm not disagreeing with the pain-points you raise though, but there could be some alternative approaches without compromising the generality of pynetbox. Maybe an internal library that uses pynetbox and implements a `create_device` that's specifically tailored to your use-case. Or even by convention, maybe something like (not tested, but _should_ work)

```
nb.dcim.interfaces.create(
    site=getattr(nb.dcim.device_roles.get(name=friendly_name), 'id', nb.dcim.device_roles.create(name=friendly_name).id)
)
...
```
