### ISSUE TITLE
Changelog not displaying results via API

### ISSUE THREAD

**Issue by cweir-tacc** [digitalocean/pynetbox#141]
Hello,

I have been trying to use the API to access the changelog for certain objects and events. when i use the .all() or .filter() commands for the endpoint, it only returns a empty list that is comma seperated. There are entries in the changelog so its not a fresh install problem. However it is only currently working when I do a .get() on a particular ID. 

Any help on getting this solved would be appreciated. Thanks

**Comment by zachmoody** [comment]
Looks like we need a model for the extras app that lets us define some custom behavior ObjectChanges. Also think we need a way to handle fields that shouldn't be turned into Records that scales better than just appending the field to `JSON_FIELDS`. Will try and get something to address these. Fwiw, the list it's returning isn't empty, each item is Record object but since they don't have a `name` field their representation in the interpreter is empty. You can still reference them by index.
