### ISSUE TITLE
Add "count" functionality

### ISSUE THREAD

**Issue by tyler-8** [digitalocean/pynetbox#158]
There are times I want to get the total count of list data, without actually needing the dataset. This is particularly handy with filtered lists. If I was using `requests`, I would just use the `limit=1` parameter and parse out the value of `count` in the API response.

But there's no way to do this in pynetbox currently. I envision some sort of API like this:

```
>>> t1_circuits_count = nb.circuits.circuits.count(type_id=2)

>>> print(t1_circuits_count)
12
```

And behind the scenes it's just getting back a single item response, but still has the `count` key. This way I could get total circuits for each circuit type very quickly, without having to pull down a dataset of thousands of rows (and far more database queries).

**Comment by pm17788** [comment]
I was struggling deciding between doing `.all(count_only=True)` and separate methods like @tyler-8  suggested. Settled on `.all_count()` being a companion to `.all()`, and`.filter_count()`companion of `.filter()`) rather than writing logic to handle *count_only* argument to `.all()` and `.filter()` methods.

In the end, it came down to the return types. `.all()` returns a list of Records, but `.all(count_only)` would return an int. That felt like I'd be setting up a future rife with TypeErrors or one full of `if instance()` checks, so having a separate `all_count()`  felt more appropriate. Happy to have been wrong.

Ended up using the https://github.com/tqdm/tqdm library for the progress bar.

The overall goal is to add:
1. `.all_count()` function to all endpoints. Returns the total count of things at the given endpoint. Example usage:
```python
if nb.dcim.devices.all_count() > 150:
    # Welp, lots of devices. Let's ask for progress, instead of just sitting there waiting.
    all_devices = nb.dcim.devices.all(progress=True)
```
2. `.filter_count()` function to all endpoints. Returns the total count of things matched by the filter arguments, so you can do clever things like: 
```python
if  nb.ipam.prefixes.filter_count(within="10.128.0.0/10", status=1 > 150):
    print("Your query is about to affect a large swatch. You sure?")
```
3. Ability to specify `.filter(progress=True)` or .`all(progress=True)`
```bash
all_devices = nb.dcim.devices.all(progress=True)
Progress: 100%|█████████████████████████████████████████████████████████████████████████████| 7326/7326 [02:18<00:00, 52.92results/s]```
