### ISSUE TITLE
Unable to retrieve available-ips

### ISSUE THREAD

**Issue by cjbirk** [digitalocean/pynetbox#16]
Trying to list all available IP's using this module is not working

```python
if __name__ == "__main__":
    nb = pynetbox.api(URL, TOKEN)
    testing_this = nb.ipam.prefixes.available_ips.get(70)
    print testing_this
```

returns

```python
Traceback (most recent call last):
  File "netboxtest.py", line 44, in <module>
    testing_this = nb.ipam.prefixes.available_ips.get(70)
AttributeError: 'Endpoint' object has no attribute 'available_ips'
```

whereas 

```python
testing_this = nb.ipam.prefixes.get(70)
```

Returns the expected subnet.

**Comment by zachmoody** [comment]
Yeah, unfortunately that's not going to work currently. The problem is that `available-ips` is something of an outlier to the rest of the endpoints in that it's hanging off `prefixes` instead of an app like `ipam`. Will be adding support for it in a future release so I'll leave this open as a reference.

**Comment by cjbirk** [comment]
Ah. Well, thanks for the fast response!
