### ISSUE TITLE
ID of Record is returned instead of Record

### ISSUE THREAD

**Issue by louis-oui** [digitalocean/pynetbox#162]
Environment
Python version: 3.6.6
NetBox version: 2.5.10
PynetBox version: 4.0.6

Steps to reproduce :
Python 3.6.6 (default, Aug 13 2018, 18:24:23) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynetbox
>>> api = pynetbox.api(
...     'http://YYYYYYYY',
...     token='XXXXXXXXX',
... )
>>>
>>> ic=api.dcim.interface_connections.all()[0]
>>> str(ic)
'xe-0/1/6'
>>> i=ic.interface_a
>>> i.name
'xe-0/1/6'
>>> i.id
1500
>>> i.url
'http://XXX/api/dcim/interfaces/1500/'
>>> i.cable
7990
>>> type(i.cable)
<class 'int'>
>>> intf=api.dcim.interfaces.get(1500)
>>> intf.name
'xe-0/1/6'
>>> intf.id
1500
>>> intf.url
>>> intf.cable
>>> type(intf.cable)
<class 'pynetbox.core.response.Record'>
>>> intf.cable.id
7990

**Expected Behavior**
type(i.cable) returns <class 'pynetbox.core.response.Record'>

**Observed Behavior**
type(i.cable) returns <class 'int'> (i.e. i.cable is the ID of cable)

**Comment by zachmoody** [comment]
Unfortunately this is due to the API only returning an int here instead of a nested response. You can get around it by loading its value into `api.dcim.cables.get(id)`. It's not exactly as simple as adding it to the model to get the desired behavior either since `Record` is expecting a dict, but may be open to a PR for if there's enough desire for it.

**Comment by louis-oui** [comment]
You are correct. Thank you.
You can see that in :
http://XXX/api/dcim/interface-connections/
