### ISSUE TITLE
pynetbox should support patching

### ISSUE THREAD

**Issue by explody** [digitalocean/pynetbox#22]
Using pynetbox, we quickly ran into scenarios where we needed to bulk-update a resource from a python dict or similar multi-value source.  But, we noticed that there didn't seem to be PATCH support, nor a way to update a resource, aside from updating an object's attributes one by one, then calling save().

It would be extremely useful to be able to do two things:

1) Update a resource, given an ID and update data, without previously fetching it as an object, i.e.
```
netbox.dcim.devices.update(1, {'key': 'value', 'otherkey': 'othervalue'})
```

2) Update a retrieved object with a dict
```
dev = netbox.dcim.devices.get(1)
dev.update({'key': 'value', 'otherkey': 'othervalue'})
dev.save()
```

**Comment by cweir-tacc** [comment]
I have now running into a similar issue and would like an elegant solution.

**Comment by zachmoody** [comment]
So the latter approach will be in the 4.0.0 release. Opted not to do a method off Endpoint because you likely wouldn't know the `id` beforehand, and something like:
```
for i in netbox.dcim.devices.filter(blah='blah'):
    i.update({{'key': 'value', 'otherkey': 'othervalue'})
```
Seems more natural and would lead to fewer queries. If I'm missing something though feel free to open a new issue and we can discuss it.
