### ISSUE TITLE
using strings for choice fields results in always updating an object

### ISSUE THREAD

**Issue by cloos** [digitalocean/pynetbox#221]
Python: 3.6.9
NetBox: 2.7.3
pynetbox: 4.2.4

NetBox 2.7.0 introduced **API Choice Fields Now Use String Values**:
https://github.com/netbox-community/netbox/releases/tag/v2.7.0

When using a string for a choice field, pynetbox always update the object, even if the data are not changed.

Here a test script:

```python
import os
import pynetbox

netbox = pynetbox.api(os.environ["NETBOX_URL"], token=os.environ["NETBOX_API_TOKEN"])
cluster = netbox.virtualization.clusters.get(name="test")
if cluster is None:
    cluster= netbox.virtualization.clusters.create(name="test", type=1)

data = dict(name="test", cluster=cluster.id, status="active")
vm = netbox.virtualization.virtual_machines.get(name=data["name"])
if vm is None:
    vm = netbox.virtualization.virtual_machines.create(data)
    print("vm '{}' created".format(data["name"]))

update = vm.update(data)
if update:
    print("vm '{}' updated".format(data["name"]))
```

Running this script multiple times always shows `vm 'test' updated`.
You see also a changelog entry for each run in NetBox.
But actually the virtual_machine data are always the same for each run, so I would not expect an update.

If you change `status="active"` to `status=1` in the script, pynetbox correctly not updates the object.

**Comment by FragmentedPacket** [comment]
I'm running into this as well. I think 2.8 will not return the ID any longer so the issue will fix itself due to the following code:
https://github.com/digitalocean/pynetbox/blob/master/pynetbox/core/response.py#L39

Is there anyway we can pass in the `return_fields` somehow? If I could just set the value to return the value, that would fix this issue. I think we can possibly accomplish this by allowing `return_fields` to be passed into the `serialize` method here:

https://github.com/digitalocean/pynetbox/blob/6a9190a41e812721ce14907205377ee85049f635/pynetbox/core/response.py#L323

This will allow it pass those into the `return_fields` when attempting to find the nested keys.

```
def serialize(self, nested=False, init=False, return_fields=None)
    if nested:
        return get_value(self, return_fields)

```
If I'm missing a way to already do this, please let me know.
