### ISSUE TITLE
Pagination doesn't work as expected

### ISSUE THREAD

**Issue by mngan** [digitalocean/pynetbox#275]
In unthreaded mode, when you have more objects than the page size, the second request will attempt to fetch _all_ of the objects, not the page size. This leads to request timeouts for very large numbers of objects. 

In threaded mode, the limit is forced to zero, which the comment says will be used to calculate the default page size. The problem here is that when the limit is set to zero, it appears all the records are returned. So the request times out. 

I have submitted pull request [#274 ](https://github.com/digitalocean/pynetbox/pull/274) which makes this behave as I would expect. But it looks like the test is now broken because the results the test is looking for I believe are also wrong. But I could be misunderstanding the intent of how get() is supposed to work.

**Comment by zachmoody** [comment]
It should paginate up to whatever your [MAX_PAGE_SIZE](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#max_page_size) NetBox setting is. You'll see timeouts if the worker exceeds its timeout trying to respond, and you might need to tune that setting to get rid of the timeouts. I would like to add more granular controls for pagination for .all() and filter(), but would need to wait for the next major release.

**Comment by tyler-8** [comment]
[copying what I wrote in the PR]

> when you have more objects than the page size, the second request will attempt to fetch all of the objects, not the page size. This leads to request timeouts for very large numbers of objects.

The default settings in NetBox for pagination are `MAX_PAGE_SIZE = 1000` and `PAGINATE_COUNT = 50` (the default `limit` if none is specified). If you specify `{"limit": 0}` in your query parameters, you will get at maximum `MAX_PAGE_SIZE` (1000 if using default) records.

The only way this behavior changes is if a NetBox admin sets their `MAX_PAGE_SIZE` to 0, which disables the limit entirely - and is a terrible idea that no one should be doing - which is why it's called out in the `pynetbox` [README](https://github.com/digitalocean/pynetbox/blob/72e62aa831e594753f232f17a6c12c4d8bbca03c/README.md#threading).

With all that in mind, if the `{"limit": 0}` is removed, then `pynetbox` will be stuck paginating at the `PAGINATE_COUNT ` size - which is quite low, at the default of 50, for most use cases. The reason that `{"limit": 0}` is used is so we can determine the largest page size available to reduce the number of pages required, which presumably gives better performance. Devices are always the exception to this because of the slowness associated with calculating config contexts.

I think a better alternative to doing this would be to provide an optional parameter for allowing the user to specify their own limit/page size.

**Comment by mngan** [comment]
Thanks. It seems my understanding of how this should work if flawed. I had assumed that the intent was to determine the PAGINATION_COUNT and keep paging at that size. I didn't realize there was another value MAX_PAGE_SIZE which is determined setting limit to zero. I think the problem is the config_context. We have 4000-5000 devices in the netbox and pynetbox will fail to fetch these. I'll try it with `exclude=config_context`.

**Comment by mngan** [comment]
Excluding the config context, does in fact fix our issue.

**Comment by parth995** [comment]
> [copying what I wrote in the PR]
> 
> > when you have more objects than the page size, the second request will attempt to fetch all of the objects, not the page size. This leads to request timeouts for very large numbers of objects.
> 
> The default settings in NetBox for pagination are `MAX_PAGE_SIZE = 1000` and `PAGINATE_COUNT = 50` (the default `limit` if none is specified). If you specify `{"limit": 0}` in your query parameters, you will get at maximum `MAX_PAGE_SIZE` (1000 if using default) records.
> 
> The only way this behavior changes is if a NetBox admin sets their `MAX_PAGE_SIZE` to 0, which disables the limit entirely - and is a terrible idea that no one should be doing - which is why it's called out in the `pynetbox` [README](https://github.com/digitalocean/pynetbox/blob/72e62aa831e594753f232f17a6c12c4d8bbca03c/README.md#threading).
> 
> With all that in mind, if the `{"limit": 0}` is removed, then `pynetbox` will be stuck paginating at the `PAGINATE_COUNT` size - which is quite low, at the default of 50, for most use cases. The reason that `{"limit": 0}` is used is so we can determine the largest page size available to reduce the number of pages required, which presumably gives better performance. Devices are always the exception to this because of the slowness associated with calculating config contexts. The timeouts you're seeing I'm guessing are from the `devices` API. There is an [open issue](https://github.com/netbox-community/netbox/issues/4559) on the NetBox repo to address config context generation performance.
> 
> I think a better alternative to doing this would be to provide an optional parameter for allowing the user to specify their own limit/page size.
> 
> [Edit]
> @zachmoody has it right though, assuming your `MAX_PAGE_SIZE` isn't set to 0, then you may want to try adjusting it to something lower than 1000. Try 500 and see if that makes any difference in your timeouts - or you'll want to try something [like this](https://github.com/digitalocean/pynetbox/issues/270#issuecomment-663806412), or adding `exclude=config_context` to your filter parameters.



**COULD YOU PLEASE ELABORATE ON WHERE NETBOX ADMIN CAN CHANGE value for "MAX_PAGE_SIZE" to 0 from GUI ?**
