### ISSUE TITLE
API virtual-machines only return primary ip address

### ISSUE THREAD

**Issue by vnStrawHat** [digitalocean/pynetbox#294]
Hello,

I have a Virtual Machine with:
- 1 virtual interface
- this virtual interface have 02 IP
- one IP mark as primary
![image](https://user-images.githubusercontent.com/4435695/96071937-4e51cb80-0ecd-11eb-90bb-f42d44ff65fb.png)

When query with API virtual-machines, the result only have primary IP. How can we get the result with all IP Address ?
I use netbox version v2.8.3

**Comment by jeremystretch** [comment]
This issue is pending closure as it does not conform to one of the [provided templates](https://github.com/netbox-community/netbox/issues/new/choose) as required by the [contributing guide](https://github.com/netbox-community/netbox/blob/master/CONTRIBUTING.md). If you'd like to request that your issue be re-opened, please first update the content so that it matches the appropriate template (this may require rewriting your issue entirely).

**Comment by tyler-8** [comment]
The `nb.virtualization.virtual_machines` endpoint only returns `VirtualMachine` objects. If you want interfaces and IP addresses you have to query the `nb.virtualization.interfaces` and `nb.ipam.ip_addresses` endpoints, filtering by the VirtualMachine ID. Reference the NetBox API docs for your installation at `http://<netbox_url>/api/docs/` to see the available filters.
