### ISSUE TITLE
Need help with a script

### ISSUE THREAD

**Issue by laboiteajb** [digitalocean/pynetbox#306]
Hello,

In my company we want to use netbox as a customer database, but with more than 200 customers I am trying to automate as much as possible to reduce the workload of technicians.

the idea is to create a script that adds or updates the data in netboc from the backup files of the network routers
it's been several days that I stuck on this problem

I would like to add vlan to an interface
devices = nb.dcim.interfaces.filter(device='CR')
interface=devices[0]

can you give me the syntax to add vlan tagged?
I'm a beginner in python sorry

**Comment by Dimaqa** [comment]
Hello! I hope this is still relevant.

First thing you need to do is to get your vlan object from netbox.
This is necessary because you will need id later:
`vlan = nb.ipam.vlans.get(name='Simple name', vid=42)`
They you can get list of device interfaces by
`interfaces_list = nb.dcim.interfaces.filter(device='Device name')`
Or even get interface that you need by specifying name
`interfaces = nb.dcim.interfaces.get(device='Device name', name='Interface name')`
And now you can update your interface by specifying mode and vlan id
```
interface.update({
    'mode' : 'One of tagged\access\tagged-all',
    'tagged_vlans' : [vlan.id] # here you need to specify list of vlan ids
})
```
