### ISSUE TITLE
get() method on Endpoint objects has incorrect behavior with >1 match

### ISSUE THREAD

**Issue by DrewBloechl** [digitalocean/pynetbox#362]
This is broken in versions 6.1.0 back through 6.0.0, I think in commit d06ca91619cf797d5e456a7836f47e132355f8dd.

Here's the bad behavior, where I've given criteria that match multiple device types, but instead of the expected ValueError I just get the first match:
```
>>> len(nbapi.dcim.device_types.filter(manufacturer='cisco'))
139
>>> nbapi.dcim.device_types.get(manufacturer='cisco')
2300
```

Here's what we want to see, from 5.3.1:
```
>>> len(nbapi.dcim.device_types.filter(manufacturer='cisco'))
139
>>> nbapi.dcim.device_types.get(manufacturer='cisco')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 141, in get
    raise ValueError(
ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead.
```

**Comment by zachmoody** [comment]
Yeah, so...this change in behavior missed the release notes. My apologies :disappointed: . I took out the exception here with the change to generators because I felt it was more trouble than it was worth. But I totally see how its current behavior can be somewhat astonishing; just didn't think there were many people relying on it. We can add it back in if I missed the mark.

**Comment by DrewBloechl** [comment]
I would definitely appreciate a return to the old behavior, since I've got code that relies on its (IMO very useful) documented semantics. :)

Looking at the current implementation, it might be as easy as using `list(itertools.islice(foo, 2))` and raising ValueError on a 2-length list, or something like that.
