### ISSUE TITLE
Unable to do Multiple Updates on an Item

### ISSUE THREAD

**Issue by MrPaulAR** [digitalocean/pynetbox#371]
This may be intended behavior but I don't see it in the documentation.

This code works fine.

```
def netbox_mark_reserved(nb_item):
  # Mark element as reserved
  nb_item.tags.remove(v_tag)
  nb_item.tags.append(r_tag)
  nb_item.save()

def netbox_mark_vacant(nb_item):
  # Mark element as vacant
  nb_item.tags.remove(r_tag)
  nb_item.tags.append(v_tag)
  nb_item.save()

nb_int = nb.dcim.interfaces.get(id)
netbox_mark_reserved(nb_int)
```

However, if later down in my script I go and revert the tags with the netbox_mark_vacant this doesn't work.

```
netbox_mark_vacant(nb_int)
```

The workaround I am using is to "refresh" nb_item with another get.

```
def netbox_mark_vacant(nb_item):
  # Mark element as vacant
  nb_item = nb.dcim.interfaes.get(nb_item.id)
  nb_item.tags.remove(r_tag)
  nb_item.tags.append(v_tag)
  nb_item.save()
```

If this is the expected behavior (likely) is there a way to make the "refresh" more generic so this function can be used for anything that supports tags?  

For what it's worth this script essentially marks an interface as reserved, does some work, then marks it as vacant.

**Comment by markkuleinio** [comment]
Does it work if you call `nb_item.full_details()` after saving the object? That's the trick I did in https://majornetwork.net/2021/01/using-tags-with-pynetbox-in-netbox-2-9/ .

**Comment by zachmoody** [comment]
Yeah, `.full_details()` would be a cleaner way of doing it. I think the root of the issue is that we've avoided dealing with a lot of state in Record objects. The cache we use to compare whether or not we send changes is only populated on init. It might be possible to deal with cases like this with some custom objects for tags and implementing `__setattr__` on Record objects. It'd add a lot of complexity I'm not sure we want to take on, but this isn't great behavior either.

**Comment by MrPaulAR** [comment]
Thanks to both of you!  .full_details() addresses my need.
