### ISSUE TITLE
Results seem to be limited at 1050 records

### ISSUE THREAD

**Issue by lamiskin** [digitalocean/pynetbox#4]
I've noticed when getting an endpoint result with an expected 4090 results (netbox UI indicates the expected record count), but seem to only be getting 1050 records.

This is happening on `nb.dcim.devices`, with either a `filter(site_id=<>)` or `.all()`. I have not tested other endpoints, but I imagine its a limit imposed by the netbox api?

Its logical to have some sort of limit and to return paginated results, but I can't find anything in the documentation regarding fetching the next batches of results etc.

Is there currently a way with pynetbox to handle this situation?

**Comment by zachmoody** [comment]
Yeah, I'm seeing it as well. I think it's due to the fairly naive way pynetbox handles pagination and the `MAX_PAGE_SIZE` (defaults to 1000) setting in NetBox. The way pagination works now is by making a request and looking for a `next` field in the response. If it's not null, then we make a second request and populate the `limit=` and `offset=` fields with the total count and a sum of objects in first response respectively. The thinking was that you'd only ever make two requests, and if you were calling `.all()` or a liberal `.filter()` then you probably needed all the results anyways. That was before `MAX_PAGE_SIZE` was a thing, and I get there's lots of scenarios where that might not be true as well. There's probably a good half dozen ways to do pagination. I'm open to ideas for a more sophisticated approach. Would prefer to not change the API too much, but if we have to, we can.

**Comment by zachmoody** [comment]
^ that should get around the limitation related to `MAX_PAGE_SIZE` for now. I'll leave the issue open for a while if anyone wants to chime in on better ways to handle pagination.
