### ISSUE TITLE
`get()` and `filter()` methods for `ipam.ip_addresses` don't work as (naïvely?) expected

### ISSUE THREAD

**Issue by mandarg** [digitalocean/pynetbox#55]
After instantiating my Netbox instance like this:

```
import pynetbox
nb = pynetbox.api("http://localhost:8000", token='mysupersecrettoken')
```

```
(Pdb) nb.ipam.ip_addresses.create(address='8.8.8.8/32')
{u'status': 1, u'last_updated': u'2018-05-01T17:52:03.678390Z', u'description': u'', u'nat_inside': None, u'created': u'2018-05-01', u'role': None, u'vrf': None, u'address': u'8.8.8.8/32', u'interface': None, u'id': 50, u'tenant': None}
(Pdb) nb.ipam.ip_addresses.get(address='8.8.8.8/32')
*** ValueError: get() returned more than one result.
(Pdb) nb.ipam.ip_addresses.get(address='8.8.8.8')
*** ValueError: get() returned more than one result.
(Pdb) nb.ipam.ip_addresses.filter(address='8.8.8.8/32')
[8.8.8.8/32, <long list of other IP addresses in my instance>]
(Pdb) nb.ipam.ip_addresses.filter(address='8.8.8.8')
[8.8.8.8/32, <long list of other IP addresses in my instance>]
```

```
(Pdb) pynetbox.__version__
'3.3.1'
```

**Comment by mandarg** [comment]
@zachmoody pointed out that the filter query should have been:
```
 nb.ipam.ip_addresses.filter(q='8.8.8.8/32')
[8.8.8.8/32]
```
...which correctly shows the address we added. Thus, this indicates two problems:

* `filter()` is returning the entire list of objects for unrecognized params (I'm guessing this should probably be tracked as a separate issue)
* `get()` is returning more than one result even though `filter()` with the correct params indicates that a single one should be returned

**Comment by zachmoody** [comment]
:wave:  Is everything working ok now using the `q=` kwarg instead of `address=`? Remember talking about it on the NTC slack, but I'm sure the history's rolled off by now. :blush:

Verified I'm not able to replicate the issue with `.get(q=x.x.x.x/x)`. Those results are understandable passing a kwarg the API doesn't understand though. No way to prevent that in pynetbox outside of doing some client-side validation.

Will close for now, but lmk if I've missed something.
